import {
  INTERPOLATION_END_OUTPUT_VALUE,
  INTERPOLATION_START_INPUT_VALUE,
  INTERPOLATION_START_OUTPUT_VALUE,
} from 'constants/animation';

const SCALE_FINAL_INPUT_VALUE = 500;

const OPACITY_FINAL_INPUT_VALUE = 250;

export const SCALE_INPUT_RANGE = [
  INTERPOLATION_START_INPUT_VALUE,
  SCALE_FINAL_INPUT_VALUE,
];

export const SCALE_OUTPUT_RANGE = [
  INTERPOLATION_START_OUTPUT_VALUE,
  INTERPOLATION_END_OUTPUT_VALUE,
];

export const OPACITY_INPUT_RANGE = [
  INTERPOLATION_START_INPUT_VALUE,
  OPACITY_FINAL_INPUT_VALUE,
];

export const OPACITY_OUTPUT_RANGE = [
  INTERPOLATION_START_OUTPUT_VALUE,
  INTERPOLATION_END_OUTPUT_VALUE,
];
