export const iconImages = {
  FilledHome: require('assets/icons/home/filled_home.png'),
  StrokedHome: require('assets/icons/home/stroked_home.png'),
  FilledLibrary: require('assets/icons/library/filled_library.png'),
  StrokedLibrary: require('assets/icons/library/stroked_library.png'),
  FilledSearch: require('assets/icons/search/filled_search.png'),
  StrokedSearch: require('assets/icons/search/stroked_search.png'),
  FilledPlay: require('assets/icons/play/filled_play.png'),
  StrokePlay: require('assets/icons/play/stroked_play.png'),
  FilledHeart: require('assets/icons/heart/filled_heart.png'),
  StrokedHeart: require('assets/icons/heart/stroked_heart.png'),
  Left: require('assets/icons/left/left.png'),
  Right: require('assets/icons/right/right.png'),
  Up: require('assets/icons/up/up.png'),
  Down: require('assets/icons/down/down.png'),
  Back: require('assets/icons/back/back.png'),
  Skip: require('assets/icons/skip/skip.png'),
  Gears: require('assets/icons/gears/gears.png'),
  ArrowDown: require('assets/icons/arrow_down/arrow_down.png'),
  MenuDots: require('assets/icons/menu_dots/menu_dots.png'),
  Plus: require('assets/icons/plus/plus.png'),
  Shuffle: require('assets/icons/shuffle/shuffle.png'),
  Pause: require('assets/icons/pause/pause.png'),
  ListPlaying: require('assets/icons/list_playing/list_playing.png'),
  Devices: require('assets/icons/devices/devices.png'),
  Repeat: require('assets/icons/repeat/repeat.png'),
};
